# This workflow will do a clean installation of node dependencies using yarn, build the source code and run tests across different versions of node. 
# The tests will produce a coverage report uploaded to CodeCov.

name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.21.3, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: yarn

    - name: Lint files
      run: yarn lint
    
    - name: Build files
      run: yarn build
    
    - name: Test the app
      run: yarn test:coverage  

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
