# This workflow will do a clean installation of node dependencies using yarn, build the source code and run tests across different versions of node. 
# The tests will produce a coverage report uploaded to CodeCov.

name: Code Coverage CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Run yarn install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    
    - name: Run yarn build
      uses: borales/actions-yarn@v4
      with:
        cmd: build
    
    - name: Test the app
      uses: borales/actions-yarn@v4
      with:
        cmd: test:coverage # will run `yarn test:coverage` command

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    
